### ISSUE TITLE
Mobile Wireframes

### ISSUE THREAD

**Issue by anthonydpaul** [anthonydpaul/remote-collab#11]
## Tasks:
- [x] Internal kick-off meeting #10 / @anthonydpaul
- [ ] Off-canvas menu #3 / everyone
- [ ] Homepage #1 / **@fakename1000**
- [ ] List View #7 / TBD
- [ ] Article View #4 / TBD

We'll have a meeting to review progress at the end of the week.
